sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

language: node_js
node_js:
- 8
- 9

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_script:
- yarn global add @angular/cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

install:
- yarn install

script:
- ng lint
- ng test --sr
- ng e2e --aot
- ng build --aot

notifications:
  email:
    on_failure: never
    on_success: never
